config/routes.rb
Rails.application.routes.draw do
  get 'janken/index'
  get 'janken/point'
  get 'janken/sen'
  get 'janken/janken'
  devise_for :users
  resources :top, :only => [:index]
  resources :posts, :only => [:show, :index, :new, :create, :edit, :update, :destroy]
  resources :users, :only => [:show, :index, :edit, :update]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index, :edit, :update, :destroy]
  root "top#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to  :room
  belongs_to  :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :entries
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/janken_controller.rb
class JankenController < ApplicationController
  def index
    @users = User.all
  end

  def point

    jankens = ["グー", "チョキ","パー"]
    program_hand = rand(3)
    player_hand = params[:player_hand].to_i
    @a = "あなたの手:#{jankens[player_hand]}, 相手の手:#{jankens[program_hand]}"
      if player_hand == program_hand
        var = true
      elsif(player_hand == 0 && program_hand == 1)||(player_hand == 1 && program_hand == 2)||(player_hand == 2 && program_hand == 0)
        @result = "あなたの勝ちです"
        var = false
      else
        @result = "あなたの負けです"
        var = false
      end

      if var == true
        flash.now[:aiko] = "あいこです。もう一回選択してください"
        render janken_janken_path
      else
        render janken_sen_path
      end
  end

  def sen
  end

  def janken
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, :only => [:create]

  def create
    if Entry.where(:user_id => current_user.id, :room_id => params[:message][:room_id]).present?
    @message = Message.create(params.require(:message).permit(:user_id, :room_id, :content).merge(:user_id => current_user.id))
    else
      flash[:alert] = "無効なユーザー"
    end
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
  end

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(params.require(:post).permit(:user_id, :content, :sex).merge(:user_id => current_user.id))
    @user = User.find(@post.user_id)
  end

  def edit
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
    if @post.user_id == current_user.id
    else
      redirect_to posts_path
      flash[:alert] = "無効なユーザー"
    end
  end

  def update
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
    if @post.user_id == current_user.id
      @post.update(params.require(:post).permit(:content, :sex))
    else
      redirect_to posts_path
      flash[:alert] = "無効なユーザー"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    @user = User.find(@post.user_id)
    if @post.user_id == current_user.id
      @post.destroy
    else
      redirect_to posts_path
      flash[:alert] = "無効なユーザー"
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, :only => [:create, :show, :index, :edit, :update]

  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
    flash[:notice] = "チャットを作成しました！"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
    @messages = @room.messages
    @message = Message.new
    @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = "無効なユーザー"
    end
  end

  def index
    @entries = current_user.entries
  end

  def edit
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
    else
      flash[:alert] = "無効なユーザー"
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
    @room.update(params.require(:room).permit(:name, :explain))
    flash[:notice] = "チャット情報が変更されました"
    redirect_back(fallback_location: root_path)
    else
      flash[:alert] = "無効なユーザー"
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :only => [:show, :index, :edit, :update]

  def show
    @user = User.find(params[:id])
    if @user.id == current_user.id
       @entries = current_user.entries.limit(3)
    else
      @room = Room.new
      @entry = Entry.new
    end
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
    else
      redirect_to posts_path
      flash[:alert] = "無効なユーザー"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.id == current_user.id
      @user.update(params.require(:user).permit(:first_name, :family_name, :self_introduction))
    else
      redirect_to posts_path
      flash[:alert] = "無効なユーザー"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/janken_helper.rb
module JankenHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/janken/index.html.erb
<h2>ミニゲーム</h2><hr>
<br><p>
<%= link_to "ジャンケンをする", janken_janken_path, class:"btn btn-success" %>
</p>
<br><hr>
<p>
  <a class="btn btn-danger"　href="/users/<%= current_user.id %>"><%= current_user.family_name %><%= current_user.first_name %>さんのユーザ情報</a>
</p>
<p>
 <%= link_to 'ユーザーリストに戻る', users_path, class:"btn btn-primary" %>
</p>
<p>
 <%= link_to 'トップに戻る', posts_path, class:"btn btn-info" %>
</p>

app/views/janken/janken.html.erb
ジャンケン<br><hr>

<%= flash.now[:aiko] %><br>
<%= link_to "グー", janken_point_path(player_hand: 0), class:"btn btn-default" %>
<%= link_to "チョキ", janken_point_path(player_hand: 1),class:"btn btn-default" %>
<%= link_to "パー", janken_point_path(player_hand: 2), class:"btn btn-default" %>
<br><br>

app/views/janken/sen.html.erb
<%= @a %><br>
<%= @result %>

<br><br>
<p>
 <%= link_to 'もう一度ジャンケンをする', janken_janken_path, class:"btn btn-success" %>
</p><hr>
<p>
  <a class="btn btn-danger"　href="/users/<%= current_user.id %>" role="button"><%= current_user.family_name %><%= current_user.first_name %>さんのユーザ情報</a>
</p>
<p>
 <%= link_to 'ユーザーリストに戻る', users_path, class:"btn btn-primary" %>
</p>
<p>
 <%= link_to 'トップに戻る', posts_path, class:"btn btn-info" %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineGame</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
   <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
     </button>
     <a href="/posts" class="navbar-brand">OnlineGame</a>
   </div>
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li><a href="/users">ユーザーリスト</a></li>
      <li><a href="/users/<%= current_user.id %>"><%= current_user.family_name %><%= current_user.first_name %>さん</a></li>
      <li><a href="/janken/index">ミニゲーム</a></li>
      <li><%= link_to "ログアウト", destroy_user_session_path, :method => :delete %></li>
      <% else %>
      <li><a href="/users/sign_up">登録する</a></li>
      <li><a href="/users/sign_in">ログインする</a></li>
      <% end %>
     </ul>
     </div>
  </div>
  <div class="container main-page">
   <% if notice %>
    <br>
    <p class="alert alert-success"><%= notice %></p>
   <% end %>
   <% if alert %>
    <br>
    <p class="alert alert-danger"><%= alert %></p>
   <% end %>
  <%= yield %>
  </div>
 </nav>
</body>
</html>

app/views/posts/create.html.erb
<h1>投稿が完了しました</h1>
<hr>
<p>名前：<%= @user.family_name %><%= @user.first_name %>様</p>
<p>内容：<%= @post.content %></p>
<p>性別：<%= @post.sex %></p>
<hr>
<p>
  <%= link_to '投稿に戻る', posts_path,class:"btn btn-info" %>
</p>

app/views/posts/destroy.html.erb
<h1>投稿を削除しました</h1>
<hr>
<p>名前：<%= @user.family_name %><%= @user.first_name %></p>
<p>内容：<%= @post.content %></p>
<p>性別：<%= @post.sex %></p>
<hr>
<p>
  <%= link_to '投稿に戻る', posts_path,class:"btn btn-info" %>
</p>

app/views/posts/edit.html.erb
<h1>投稿を編集する</h1>
<hr>
<%= form_for @post do |f| %>
  <p>内容</p>
  <%= f.text_area :content, :class => "form-control" %>
  <br>
  <p>性別</p>
  <%= f.text_field :sex, :class => "form-control" %>
  <br>
  <hr>
  <%= f.submit "変更する" %>
<% end %>
<hr>
<p>
  <%= link_to '投稿に戻る', posts_path,class:"btn btn-info" %>
</p>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<hr>
<% @posts.each do |p| %>
  <p><a href="/users/<%= p.user_id %>"><%= User.find(p.user_id).family_name %><%= User.find(p.user_id).first_name %>さん</a>の投稿</p>
  <h3><a href="/posts/<%= p.id %>"><%= p.content %></a></h3>
  <hr>
<% end %>
<p>
  <%= link_to '新しく投稿する', new_post_path, class:"btn btn-info"  %>
</p>

app/views/posts/new.html.erb
<h1>投稿を作る</h1>
<hr>
<%= form_for @post do |f| %>
  <p>内容</p>
  <%= f.text_area :content, :class => "form-control my-form" %>
  <br>
  <p>性別</p>
  <%= f.text_field :sex, :class => "form-control my-form" %>
  <hr>
  <%= f.submit "登録する", :class => "btn btn-primary"%>
<% end %>
<hr>
<p>
<%= link_to 'トップに戻る', posts_path, class:"btn btn-info" %>
</p>

app/views/posts/show.html.erb
<h1>投稿</h1>
<hr>
<p><%= @user.family_name %><%= @user.first_name %>さん</p>
<h4><%= @post.content %></h4>
<small><%= @post.created_at %>：<%= @post.sex %></small>
<hr>
<p>
 <%= link_to 'トップに戻る', posts_path, class:"btn btn-info" %>
</p>
<% if user_signed_in? %>
 <% if @post.user_id == current_user.id %>
  <p><a href="/posts/<%= @post.id %>/edit" class="btn btn-success">投稿を編集する</a></p>
  <p><a href="/posts/<%= @post.id %>" data-method="delete" class="btn btn-danger">投稿を削除する</a></P>
 <% end %>
<% end %>

app/views/posts/update.html.erb
<h1>投稿を変更しました。</h1>
<hr>
<p>名前：<%= @user.family_name %><%= @user.first_name %></p>
<p>内容：<%= @post.content %></p>
<p>性別：<%= @post.sex %></p>
<hr>
<%= link_to 'トップに戻る', posts_path, class:"btn btn-info" %>

app/views/rooms/edit.html.erb
<h2>チャット情報を編集する</h2>
<hr>
<%= form_for @room do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :class => "form-control my-form", :placeholder => "名前を入力" %>
  <br>
  <%= f.label :explain %>
  <%= f.text_area :explain, :class => "form-control my-form", :size => "30x10", :placeholder => "説明を入力" %>
  <br>
  <%= f.submit "変更する", :class => "btn btn-success" %>
<% end %>
<hr>
<p><a href="/rooms/<%= @room.id %>" class="btn btn-primary">チャット情報に戻る</a></p>
<p>
 <%= link_to 'トップに戻る', posts_path, class:"btn btn-info" %>
</p>

app/views/rooms/index.html.erb
<h1>チャット一覧</h1>
<hr>
<% @entries.each do |e| %>
  <a href="/rooms/<%= e.room_id %>"><%= e.room.name %></a>
  <hr>
<% end %>
<p><a href="/users/<%= current_user.id %>" class="btn btn-primary"><%= current_user.family_name %> <%= current_user.first_name %>さんの情報に戻る</a></p>
<p>
<%= link_to 'トップに戻る', posts_path, class:"btn btn-info" %>
</p>

app/views/rooms/show.html.erb
<br>
<div class="row">
  <div class="col-xs-3 text-center">
    <h4><%= @room.name %></h4>
    <h4><small><%= @room.explain %></small></h4>
    <hr>
    <h4>参加者</h4>
    <% @entries.each do |e| %>
      <h5><strong><a href="/users/<%= e.user.id %>"><%= e.user.family_name %> <%= e.user.first_name %>さん</a></strong></h5>
    <% end %>
    <hr>
    <a href="/rooms/<%= @room.id %>/edit" class="btn btn-success">情報を編集する</a>
  </div>
  <div class="col-xs-9">
    <% if @messages.present? %>
      <% @messages.each do |m| %>
        <% if m.user_id == current_user.id %>
          <h4 class="text-right">
          <p class="alert alert-success">
          <%= m.content %>
          <br><br>
          <small><strong><a href="/users/<%= m.user_id %>"><%= m.user.family_name %> <%= m.user.first_name %>さん</a></strong></small>
          </p>
          </h4>
        <% else %>
          <h4 class="text-left">
          <p class="alert alert-info">
          <%= m.content %>
          <br><br>
          <small><strong><a href="/users/<%= m.user_id %>"><%= m.user.family_name %> <%= m.user.first_name %>さん</a></strong></small>
          </p>
          </h4>
        <% end %>
      <% end %>
    <% else %>
      <br>
      <h3 class="text-center">メッセージはまだありません</h3>
      <br>
    <% end %>
    <hr>
    <%= form_for @message do |f| %>
      <%= f.text_field :content, :class => "form-control myform", :placeholder => "メッセージを入力して下さい" %>
      <%= f.hidden_field :room_id, :value => @room.id %>
      <br>
      <div class="text-center">
        <%= f.submit "投稿する", :class => "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/top/index.html.erb
<h1>ようこそ</h1>
<br>
<a href="/posts" class="btn btn-primary">投稿一覧を見る</a>

app/views/users/edit.html.erb
<h1>ユーザー情報を編集する</h1>
<hr>
<%= form_for @user do |f| %>
  <p>名字</p>
  <%= f.text_field :family_name, :class => "form-control my-form" %>
  <p>名前</p>
  <%= f.text_field :first_name, :class => "form-control my-form" %>
  <p>自己紹介</p>
  <%= f.text_area :self_introduction, :class => "form-control my-form" %>
  <hr>
  <%= f.submit "登録する", :class => "btn btn-primary" %>
<% end %>
<hr>
<p>
  <%= link_to 'ユーザーリストに戻る', users_path, class:"btn btn-primary" %>
</p>

app/views/users/index.html.erb
<h1>ユーザーリスト</h1>
<hr>
<% @users.each do |u| %>
  <p><a href="/users/<%= u.id %>"><%= u.family_name %><%= u.first_name %>さん</a></p>
  <hr>
<% end %>
<p>
 <%= link_to 'トップに戻る', posts_path, class:"btn btn-info" %>
</p>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-6">
   <h1>ユーザー情報</h1>
   <hr>
   <p>名前：<%= @user.family_name %><%= @user.first_name %>さん</p>
   <p>自己紹介：<%= @user.self_introduction %></p>
   <br>
   <% if @user.id == current_user.id %>
    <p><a href="/users/<%= @user.id %>/edit" class="btn btn-success">ユーザー情報を編集する</a>
    <% else %>
      <%= form_for @room do |f| %>
      　<%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, :value => @user.id %>
      <% end %>
      <%= f.submit "チャットを始める", :class => "btn btn-warning" %>
    <% end %>
   <% end %>
  </div>
  <% if @user.id == current_user.id %>
    <div class="col-xs-6">
      <h1>チャット一覧</h1>
      <hr>
      <% @entries.each do |e| %>
        <p><a href="/rooms/<%= e.room.id %>"><strong><%= e.room.name %></strong></a></p>
        <hr>
      <% end %>
      <p>
       <%= link_to 'チャット一覧を見る', rooms_path, class:"btn btn-info" %>
      </p>
    </div>
  <% end %>
</div>
<hr>
<p>
 <%= link_to 'ユーザーリストに戻る', users_path, class:"btn btn-primary" %>
</p>
<hr>
<p>
 <%= link_to 'トップに戻る', posts_path, class:"btn btn-info" %>
</p>

app/views/users/update.html.erb
<h1>ユーザー情報を変更しました。</h1>
<hr>
<p>名前：<%= @user.family_name %><%= @user.first_name %>さん</p>
<p>自己紹介：<%= @user.self_introduction %></p>
<hr>
<p>
  <%= link_to 'ユーザーリストに戻る', users_path, class:"btn btn-primary" %>
</p>
<p><a href="/users/<%= @user.id %>/edit" class="btn btn-success">ユーザー情報の編集に戻る</a></p>
<p>
  <%= link_to 'トップに戻る', posts_path, class:"btn btn-info" %>
</p>